apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: smarman/py-tst
        ports:
        - containerPort: 80
