apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpine-pyapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine-pyapp
    spec:
      containers:
      - name: alpine-pyapp
        image: smarman/py-tst
        ports:
        - containerPort: 80
